config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'estimates#index'

  scope '/estimate' do
    post '/address', to: 'estimates#address'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController

  def index
  end

  def address
    estimate = HomeEvaluator.new(
      address: estimate_params,
      estimator: Estimator.new,
      formatter: HomeEstimateFormatter.new
    ).evaluate

    respond_to do |format|
      if estimate[:success?]
        @estimate = estimate[:results]
        format.html { render :show }
      else
        format.html { redirect_to root_path, flash: { error: estimate[:error] } }
      end
    end
  end

  private
    def estimate_params
      params.require(:address).permit(white_listed_params)
    end

    def white_listed_params
      %w(street_1 street_2 state city postcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
  def translate_key(key)
    case key
      when :homedetails
        'Home Details'
      when :graphsanddata
        'Graphs and Data'
      when :mapthishome
        'Map this Home'
      when :comparables
        'Comparables'
      when :overview
        'Overview'
      when :for_sale_by_owner
        'For Sale by Owner'
      when :for_sale
        'For Sale'
      else
        'of interest'
    end
  end
end

app/views/estimates/_estimate.html.erb
<div>
  <h3><%= label_tag :links, 'Links of Interest:' %></h3>
  <% estimate[:links].each do |k,v| %>
    <%= link_to translate_key(k), v, target: '_blank'  %><br/>
  <% end %>
  <h3><%= label_tag :price, 'Price:' %></h3>
  <p>The home values at <%= number_to_currency(estimate[:price]) %></p>
  <p>On the low end the home values at <%= number_to_currency(estimate[:range][:low]) %></p>
  <p>On the high end the home values at <%= number_to_currency(estimate[:range][:high]) %></p>
  <h3><%= label_tag :last_updated, 'Last Updated:' %></h3>
  <p>These estimates were last update on <%= estimate[:last_updated] %></p>
</div>

app/views/estimates/_form.html.erb
<%= simple_form_for :address, url: address_path do |f| %>
    <%= f.input :street_1, as: :string %>
    <%= f.input :street_2, as: :string %>
    <%= f.input :city, as: :string %>
    <%= f.input :state, as: :string %>
    <%= f.input :postcode, as: :string %>

    <div class="actions">
      <%= f.submit 'Estimate Address Value' %>
    </div>
<% end %>

app/views/estimates/index.html.erb
<h1>Estimates</h1>
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>
<%= render 'form', estimate: @estimate %>

app/views/estimates/show.html.erb
<h1>Estimate</h1>
<h2>The Estimate results for the address</h2>
<%= render partial: 'estimate', locals: {estimate: @estimate} %>
<%= link_to 'Back to Estimate', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiConsumer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>